image:
  file: Dockerfile

ports:
  - port: 8080
    onOpen: ignore
tasks:
  - init: mvn clean install
    command: cd app && mvn bnd-run:run
  - command: gp preview $(gp url 8080)/rest/upper/welcome
    openIn: right